name:                tron
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- matrix

library:
  source-dirs: src

executables:
  tron-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tron
    - matrix

tests:
  tron-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tron
    - tasty
    - tasty-hunit
